# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5967edca913f57eccbca2c08f0963695b0d5c12646ef9d41a087f4ae120a0a9179c1955068e5db5c3692661d9300fb48da78f4feff9124ef4f6c4a13dafae33

test:
  secret_key_base: c69f1919f7deb122276d42d576bce87556d35138782392f79677c2185f852582cd54c97b004b699d7f1d6c0ec320e3c482bc78c714e32a48bb004cd902f5af6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
